---
# tasks file for nginx-source

- name: YUM install epel-release package.
  yum: name=epel-release state=present
  when: ansible_os_family == "RedHat"

- name: YUM install package(s).
  yum: name={{ item }} state=present
  with_items:
    - gmp-devel
    - gcc
    - openssl-devel
    - readline-devel
    - expat-devel
    - libxml2-devel
    - freetds-devel
    - pcre-devel
    - automake
    - autoconf
    - libtool
    - make
    - perl
    - git
  when: ansible_os_family == "RedHat"

- name: Create '{{ nginx_src_dir }}' directory.
  file: path={{ nginx_src_dir }} state=directory

- name: Download NGINX source code.
  get_url: url=http://nginx.org/download/nginx-{{ nginx_version }}.tar.gz dest={{ nginx_src_dir }}/nginx-{{ nginx_version }}.tar.gz

- name: Untar and gunzip NGINX source code.
  unarchive: src={{ nginx_src_dir }}/nginx-{{ nginx_version }}.tar.gz dest={{ nginx_src_dir }} creates={{ nginx_src_dir }}/nginx-{{ nginx_version }} copy=no

- name: Checking local Git directory.
  stat: path=/{{ nginx_src_dir}}/ngx_http_substitutions_filter_module
  register: local_git_dir

- name: Clone 'yaoweibin/ngx_http_substitutions_filter_module' Git repository.
  git: repo=https://github.com/yaoweibin/ngx_http_substitutions_filter_module.git dest={{ nginx_src_dir }}/ngx_http_substitutions_filter_module clone=yes force=yes
  when: local_git_dir.stat.exists == False

- name: Template '/lib/systemd/system/nginx.service' file.
  template: src=systemd_nginx.j2 dest=/lib/systemd/system/nginx.service mode=0644

- name: Create '/etc/nginx' directory.
  file: path=/etc/nginx state=directory

- name: Create '/etc/nginx/conf.d' directory.
  file: path=/etc/nginx/conf.d state=directory

- name: Create '/var/log/nginx' directory.
  file: path=/var/log/nginx state=directory

- name: Create 'nginx' group.
  group: name=nginx state=present

- name: Create 'nginx' user.
  user: name=nginx groups=nginx state=present

- name: Install NGINX from source code.
  command: creates={{ nginx_prefix }} chdir={{ nginx_src_dir }}/nginx-{{ nginx_version }} {{ item }}
  with_items:
  - ./configure --user=nginx --group=nginx --sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --with-http_ssl_module --with-http_stub_status_module --add-module={{ nginx_src_dir }}/ngx_http_substitutions_filter_module
  - make install

- name: Set PID path in '/etc/nginx/nginx.conf' file.
  lineinfile: dest=/etc/nginx/nginx.conf regexp="^#pid" line="pid        /run/nginx.pid" backrefs=yes
